### ISSUE TITLE
program crashes internally but still writes VCF and successfully returns 0

### ISSUE THREAD

**Issue by pjedge** [aquaskyline/Clairvoyante#28]
I'm using the precomputed model for AJ son to call variants using the NA12878 PacBio 44x data from GIAB (sorted_final_merged.bam). On chromosome 4, the variant calling program crashes internally but still writes an output VCF and returns 0.

```
clairvoyante.py callVarBam        --chkpnt_fn trainedModels/fullv3-pacbio-ngmlr-hg002-hg19/learningRate1e-3.epoch999        --ref_fn data/genomes/hg19.fa        --bam_fn data/NA12878.1000g/aligned_reads/pacbio/pacbio.blasr.all.44x.bam        --ctgName chr4        --call_fn extra_data/NA12878.1000g/variants/clairvoyante.pacbio.blasr.44x.unfiltered/4.vcf.tmp        --sampleName NA12878        --threshold 0.2        --minCoverage 4        --threads 4
```

Here's the end of the stderr from the execution:
```
Processed 25116000 tensors
Processed 25117000 tensors
Processed 25118000 tensors
Processed 25119000 tensors
Processed 25120000 tensors
Processed 25121000 tensors
Processed 25122000 tensors
Processed 25123000 tensors
Processed 25124000 tensors
Processed 25125000 tensors
Processed 25126000 tensors
Traceback (most recent call last):
  File "/home/pedge/git/longshot_study/.snakemake/conda/7c00edba/bin/dataPrepScripts/CreateTensor.py", line 307, in <module>
    main()
  File "/home/pedge/git/longshot_study/.snakemake/conda/7c00edba/bin/dataPrepScripts/CreateTensor.py", line 303, in main
    OutputAlnTensor(args)
  File "/home/pedge/git/longshot_study/.snakemake/conda/7c00edba/bin/dataPrepScripts/CreateTensor.py", line 197, in OutputAlnTensor
    centerToAln[center][-1].append( (refPos, 0, refSeq[refPos - (0 if args.refStart == None else (args.refStart - 1))], SEQ[queryPos] ) )
IndexError: string index out of range
Processed 25126859 tensors
Total time elapsed: 40853.00 s
Traceback (most recent call last):
  File "/home/pedge/git/longshot_study/.snakemake/conda/7c00edba/bin/dataPrepScripts/ExtractVariantCandidates.py", line 312, in <module>
    main()
  File "/home/pedge/git/longshot_study/.snakemake/conda/7c00edba/bin/dataPrepScripts/ExtractVariantCandidates.py", line 308, in main
    MakeCandidates(args)
  File "/home/pedge/git/longshot_study/.snakemake/conda/7c00edba/bin/dataPrepScripts/ExtractVariantCandidates.py", line 209, in MakeCandidates
    can_fp.stdin.write(outline)
IOError: [Errno 32] Broken pipe: '<fdopen>'
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
```

What should I do?

EDIT: I realized I was tagging with the wrong --sampleName, edited to reduce confusion but that wouldn't have an effect on this output

**Comment by aquaskyline** [comment]
The error message suggests that a read alignment is out of the range of the reference provided.
