### ISSUE TITLE
TypeError in callVarBam.py

### ISSUE THREAD

**Issue by aechchiki** [aquaskyline/Clairvoyante#4]
Hi @aquaskyline, 

thanks for delivering this tool! might be my only hope for variant calling from a bam file - that's all I have for the moment, alongside an assembled not-too-bad draft genome.

I was thus trying to call variants on whole genome - [section](https://github.com/aquaskyline/Clairvoyante#how-to-call-variant-directly-from-bam). 

### Error

If I leave pypy in $PATH, get an error on script execution:
```
$ python ../clairvoyante/callVarBam.py --ref_fn ../../amphioxus/hm2/amphio_A_ref_D.fa --bam_fn ../../amphioxus/hm2/ph_on_hm2/aligned.bam --call_fn test_amphio
Traceback (most recent call last):
  File "../clairvoyante/callVarBam.py", line 218, in <module>
    main()
  File "../clairvoyante/callVarBam.py", line 214, in main
    Run(args)
  File "../clairvoyante/callVarBam.py", line 65, in Run
    chkpnt_fn = CheckFileExist(args.chkpnt_fn, sfx=".meta")
  File "../clairvoyante/callVarBam.py", line 46, in CheckFileExist
    if not os.path.isfile(fn+sfx):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This looks like a classical python2/3 confusion, which I don't really understand because 

> Clairvoyante was written in Python2 (tested on Python 2.7.10 in Linux and Python 2.7.13 in MacOS).

### Environment

```
$ python --version
Python 2.7.12
$ pip -V
pip 18.1 from /scratch/beegfs/monthly/aechchik/Clairvoyante/pypy-5.8-linux_x86_64-portable/site-packages/pip (python 2.7)

$ pip show tensorflow   
$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.5.0

$ pip show blosc
Name: blosc
Version: 1.6.2
Summary: Blosc data compressor
Home-page: http://github.com/blosc/python-blosc
Author: Francesc Alted
Author-email: faltet@gmail.com
License: https://opensource.org/licenses/BSD-3-Clause
Location: /Home/aechchik/.local/lib/pypy2.7/site-packages
Requires:
Required-by:

$ pip show intervaltree
Name: intervaltree
Version: 2.1.0
Summary: Editable interval tree data structure for Python 2 and 3
Home-page: https://github.com/chaimleib/intervaltree
Author: Chaim-Leib Halbert, Konstantin Tretyakov
Author-email: chaim.leib.halbert@gmail.com
License: Apache License, Version 2.0
Location: /scratch/beegfs/monthly/aechchik/Clairvoyante/pypy-5.8-linux_x86_64-portable/site-packages
Requires: sortedcontainers
Required-by:

$ pip show numpy
Name: numpy
Version: 1.15.4
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@python.org
License: BSD
Location: /Home/aechchik/.local/lib/pypy2.7/site-packages
Requires:
Required-by:
```

### Error

If I remove pypy in $PATH, get an error for pypy not found:
```
$ python ../clairvoyante/callVarBam.py --ref_fn ../../amphioxus/hm2/amphio_A_ref_D.fa --bam_fn ../../amphioxus/hm2/ph_on_hm2/aligned.bam --call_fn test_amphio
which: no pypy in (/software/UHTS/Analysis/samtools/1.8/bin:/home/aechchik/.local/bin:/mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/etc:/mnt/common/lsf/9.1/linux2.6-glibc2.3-x86_64/bin:/software/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/software/var/lib/snapd/snap/bin:/home/aechchik/bin/)
Error: pypy executable not found
```

Anyways I thought this script was [not compatible with pypy](https://github.com/aquaskyline/Clairvoyante/#folder-stucture-and-program-descriptions) anyways 

> Model Training and Variant Caller Scripts. Scripts in this folder are NOT compatible with pypy. Please run with python.

### Environment
```
$ python --version
Python 2.7.12
$ pip -V
pip 18.1 from /home/aechchik/.local/lib/python2.7/site-packages/pip (python 2.7)

$ pip show tensorflow   
$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.5.0

$ pip show numpy
Name: numpy
Version: 1.15.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /software/lib64/python2.7/site-packages
Requires:
Required-by: tensorflow, tensorflow-tensorboard, tensorboard, Keras-Preprocessing, Keras-Applications, pbh5tools, pbcore, xarray, weblogo,
 torchvision, Theano, seaborn, scipy-sugar, pytest-doctestplus, pyqtgraph, pyplink, PeakUtils, patsy, optimix, numpy-sugar, ndarray-listen
er, nb2plots, MOFA, matplotlib-venn, limix, limix-plot, limix-core, glimix-core, ggplot, colormath, brent-search, tables, pandas, pandas-p
link, numexpr, numba, netCDF4, matplotlib, limix-legacy, liknorm, hdmedians, h5py, fastcluster, cyvcf2, cftime, Bottleneck, biopython, bco
lz

$ pip show blosc
Name: blosc
Version: 1.5.1
Summary: Blosc data compressor
Home-page: http://github.com/blosc/python-blosc
Author: Francesc Alted, Valentin Hänel
Author-email: faltet@gmail.com, valentin@haenel.co
License: http://www.opensource.org/licenses/mit-license.php
Location: /software/lib64/python2.7/site-packages
Requires:
Required-by:

$pip show intervaltree
Name: intervaltree
Version: 2.1.0
Summary: Editable interval tree data structure for Python 2 and 3
Home-page: https://github.com/chaimleib/intervaltree
Author: Chaim-Leib Halbert, Konstantin Tretyakov
Author-email: chaim.leib.halbert@gmail.com
License: Apache License, Version 2.0
Location: /Home/aechchik/.local/lib/python2.7/site-packages
Requires: sortedcontainers
Required-by:
```

I  am not really sure on how to proceed, do you have a hint on this? 

Any help would be greatly appreciated

Thanks, 
Amina

**Comment by aquaskyline** [comment]
To use calVarBam.py, you need to provide a trained model with the --chkpnt_fn option.

**Comment by aechchiki** [comment]
ok thanks, sorry.
