### ISSUE TITLE
Error when no variant identified as result of low coverage

### ISSUE THREAD

**Issue by MeHelmy** [aquaskyline/Clairvoyante#6]
In case of calling SNPs and there is no sufficient coverage to support the variant,This error is raised;

elay 3 seconds before starting variant calling ...Delay 7 seconds before starting variant calling ...Delay 5 seconds before starting variant calling ...

```
Loading model ...
Loading model ...
Loading model ...
Traceback (most recent call last):
  File "/stornext/snfs5/next-gen/scratch/fritz/centra_programs_pipelines/conda3_64/envs/clairvoyante-1.0.0-1/bin/dataPrepScripts/ExtractVariantCandidates.py", line 316, in <module>
    main()
  File "/stornext/snfs5/next-gen/scratch/fritz/centra_programs_pipelines/conda3_64/envs/clairvoyante-1.0.0-1/bin/dataPrepScripts/ExtractVariantCandidates.py", line 312, in main
    MakeCandidates(args)
  File "/stornext/snfs5/next-gen/scratch/fritz/centra_programs_pipelines/conda3_64/envs/clairvoyante-1.0.0-1/bin/dataPrepScripts/ExtractVariantCandidates.py", line 168, in MakeCandidates
    matches.append( (refPos, SEQ[queryPos]) )
```

Thanks,

**Comment by fritzsedlazeck** [comment]
Just to clarify it is clear that this error is provided but I think it is easier for the user if you catch it and provide some warning. 
Cheers
Fritz

**Comment by aquaskyline** [comment]
Noted, @chaklim please look into the error
